config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :batches, except: %i[destroy edit update] do
    resources :costs, only: %i[create show update destroy]
    resources :users, only: %i[index destroy]
  end
  resources :bookings, only: [:create] do
    member do
      patch :accept
      patch :pending
    end
  end

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :batches
  has_many :bookings


  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to batches_path if current_user.admin == false

    @batch = Batch.find(params[:batch_id])
    @bookings = @batch.bookings.where(status: "Pending")
    @students = @batch.bookings.where(status: "Accepted").map do |booking|
      User.find(booking.user_id)
    end

    if params[:query].present?
      @student_search = []
      @students.each do |individual|
        if individual.first_name.downcase == params[:query].downcase || individual.last_name.downcase == params[:query].downcase
          @student_search << individual

        end
      end
      @students = @student_search
      # @student = User.joins(:batch).where(sql_query, query: "%#{params[:query]}%")
    end
  end

  # to edit students profile

  # def update
  #   @batch = Batch.find(params[:batch_id])
  #   @user = current_user
  #   if @user.update(student_params)
  #     redirect_to batch_users_path(@batch)
  #   else
  #     render 'edit'
  #   end
  # end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    # @batch = Batch.find(params[:batch_id])
    redirect_to batch_users_path
  end

  # private

  # def student_params
  #   params.require(:user).permit(:first_name, :last_name, :email, :photo)
  # end

end

app/views/users/index.html.erb
<!-- Section 1 -->
<section class="relative py-10 overflow-hidden bg-white px-16">
  <span class="absolute top-0 right-0 flex flex-col items-end mt-0 opacity-100">
      <span class="container hidden w-screen h-32 max-w-xs mt-20 transform rounded-full rounded-r-none md:block md:max-w-xs lg:max-w-lg 2xl:max-w-3xl bg-blue-50"></span>
  </span>

  <span class="absolute bottom-0 left-0"> </span>

  <div class="container relative mx-auto max-w-8xl">
    <%= link_to batch_path(@batch) do %>
      <span class="w-20 text-lg bg-transparent font-medium text-start cursor-pointer hover:underline rounded-lg" style="color: #0A2540"><i class="fas fa-angle-left"></i> Go back</span>
    <% end %>
    <p class="mt-3 font-medium tracking-wide uppercase" style="color: #0A2540">Welcome to students page <%= @batch.name %></p>


    <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-2">
      <div class="lg:col-span-2 md:col-span-1">
        <h2 class="relative max-w-lg mt-3 mb-0 text-4xl font-semibold lg:text-5xl" style="color: #0A2540">Meet all the faces<br>of your cohort</h2>
      </div>

      <%# -----search bar ------ %>
      <div>
        <div class="mt-2">
          <%= form_tag(batch_users_path, method: :get, class: "flex") do %>
            <%= text_field_tag :query, params[:query], autocomplete: "off", placeholder: "Search Students", class: "pl-3 my-3 border-t border-l border-b rounded-l-lg"  %>
            <%= submit_tag "Search", class: "w-20 text-sm font-medium text-end cursor-pointer py-2 px-4 text-white my-3 rounded-r-lg", style:"background-color: #0A2540"%>
          <% end %>
        </div>
      </div>
      <%# --------end------- %>

      <!-- Add student -->
      <div class="mb-3">
        <div class="flex justify-left md:pl-0 lg:ml-12 mt-3 pt-1 my-8 border-gray-50">
          <details class = "absolute z-30 w-60">
            <summary>Add a Student</summary>
            <% if @bookings.length < 1 %>
              <div class="flex">
                <div>
                  No students have applied
                </div>
              </div>
            <% end %>
            <% @bookings.each do |booking| %>
              <div class="flex">
                <div>
                  <%= "#{User.find(booking.user_id).first_name} #{User.find(booking.user_id).last_name}" %>
                </div>
                <%= form_tag accept_booking_path(booking), method: :patch, class: "ml-2" do %>
                  <%= button_tag(type: "submit", class: "btn btn-primary submit-search") do%>
                    <p class="text-gray-400 font-normal">  Add <i class="fas fa-angle-right"></i></p>
                  <% end %>
                <% end %>

                <% if "#{User.find(booking.user_id).first_name} #{User.find(booking.user_id).last_name}" %>
                <% end %>
              </div>
            <% end %>
          </details>
        </div>
      </div>
    </div>

    <%# Student Grid %>
    <div class="grid w-full gap-x-10 gap-y-5 xs:grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-6">
      <% @students.each do |student| %>
        <div class="flex flex-col justify-between items-center col-span-1 transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105 rounded-2xl px-4 py-4 mt-0" id="student-card">
          <div class="relative p-5">
            <div class="absolute z-10 w-full h-full -mt-5 -ml-5 rounded-full rounded-tr-none bg-green-50">
            </div>
            <% if student.photo.key %>
              <%= cl_image_tag student.photo.key, crop: :fill, class: "relative z-20 w-full rounded-full"%>
            <% end %>
          </div>
          <div class="mt-3 space-y-2 text-left">
            <div class="space-y-1 text-lg font-medium leading-6">
              <h3><%= student.first_name %> <%= student.last_name %></h3>
              <p class="text-gray-600 text-sm w-10"><%= student.email %></p>
            </div>
            <div class="text-sm px-4 py-1 my-0 bg-red-400 cursor-pointer hover:bg-red-600 text-white rounded-lg show-modal text-center">
              <%= form_tag pending_booking_path(Booking.where(user: student)[0]), method: :patch, class: "ml-2" do %>
                <%= button_tag(type: "submit", class: "btn btn-primary submit-search") do%>
                  Remove student
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>