config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :batches, except: %i[destroy edit update] do
    resources :costs, only: %i[create show update destroy]
    resources :users, only: %i[index destroy]
  end
  resources :bookings, only: [:create] do
    member do
      patch :accept
      patch :pending
    end
  end

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/views/pages/home.html.erb
<!-- Section 1 -->
<section class="w-full px-6 g-white mb-0" style="padding-top: 10%">
    <div>

        <!-- Main Hero Content -->
        <div class="px-0 text-center mx-auto">
            <h1 class="font-extrabold leading-none text-center text-gray-900 md:text-center">
            <span class="text-5xl md:text-7xl leading-none lg:text-8xl linear-wipe inline md:block pt-0 pb-4">Friendly</span>
            <span class="text-5xl md:text-7xl leading-none lg:text-8xl linear-wipe-2 inline md:block py-0 pb-4">Break Even Point</span>
            <span class="text-5xl md:text-7xl leading-none lg:text-8xl linear-wipe-3 inline md:block pt-0 pb-4">Calculator for your Staff</span>
              </h1>

            <div class="flex flex-col items-center mt-12 text-center">
                <span class="relative inline-flex w-full md:w-auto justify-center">
                  <%= link_to batches_path do %>
                    <div class="learn-more-start-now">
                      <span class="circle-start-now" aria-hidden="true">
                        <span class="icon arrow"></span>
                      </span>
                      <span class="button-text-start-now">Start Now</span>
                    </div>
                  <% end %>
                </span>
            </div>
        </div>
        <!-- End Main Hero Content -->

    </div>
</section>