config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :batches, except: %i[destroy edit update] do
    resources :costs, only: %i[create show update destroy]
    resources :users, only: %i[index destroy]
  end
  resources :bookings, only: [:create] do
    member do
      patch :accept
      patch :pending
    end
  end

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :costs
  validates :name, presence: true
  validates :tuition_cost, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  def index
    @user = current_user
    @batches = @user.batches
    @net_income_arr = []
    @batches.each do |batch|
      batch_days = batch.end_date - batch.start_date
      @net_income_arr << net_income_calc(batch, batch_days).round(2)
    end
    @batch = Batch.new
    @hidden = "hidden"

    if current_user.admin == false
      @batches = Batch.all
      @booking = Booking.new
    end
  end

  def show
    redirect_to batches_path if current_user.admin == false

    @hidden = "hidden"
    @hidden_cost = "hidden"
    @batch = Batch.find(params[:id])
    @costs = @batch.costs
    @cost = Cost.new
    @students = @batch.bookings.where(status: "Accepted").map do |booking|
      User.find(booking.user_id)
    end

    @batch_days = @batch.end_date - @batch.start_date
    @current_net_income = net_income_calc(@batch, @batch_days).round(2)
    @break_even = break_even_calc(@batch, @batch_days).round(2)

    # for the graph
    graph_quantity = (@break_even.round * 3) + 10
    @net_income_data_arr = net_income_data(graph_quantity, @batch, @batch_days)
    @variable_income_data_arr = variable_income_data(graph_quantity, @batch)
    @total_cost_data_arr = total_cost_data(graph_quantity, @batch, @batch_days)
    @variable_cost_data_arr = variable_cost_data(graph_quantity, @batch)

    @max_value = [@net_income_data_arr.max[1], @variable_income_data_arr.max[1], @total_cost_data_arr.max[1], @variable_cost_data_arr.max[1]].max.round + 10
    @min_value = [@net_income_data_arr.min[1], @variable_income_data_arr.min[1], @total_cost_data_arr.min[1], @variable_cost_data_arr.min[1]].min.round - 10
  end

  def create
    @user = current_user
    @batches = current_user.batches
    @batch = Batch.new(batch_params)
    @batch.user = @user
    if @batch.save
      redirect_to batches_path
    else
      @hidden = ""
      render :index
    end
  end

  private

  def batch_params
    params.require(:batch).permit(:name, :tuition_cost, :start_date, :end_date)
  end

  # For dashboard data infobox
  def total_fixed_cost_calc(batch, days)
    return batch.costs.where(kind: "Fixed", recurring: "One Time").sum(&:amount) + (batch.costs.where(kind: "Fixed", recurring: "Daily").sum(&:amount) * days) + (batch.costs.where(kind: "Fixed", recurring: "Weekly").sum(&:amount) * (days/7.0)) + (batch.costs.where(kind: "Fixed", recurring: "Monthly").sum(&:amount) * (days/30.437)) + (batch.costs.where(kind: "Fixed", recurring: "Yearly").sum(&:amount) * (days/365.0))
  end

  def break_even_calc(batch, days)
    total_fixed_cost = total_fixed_cost_calc(batch, days)
    total_variable_cost = batch.costs.where(kind: "Variable").sum(&:amount)
    variable_revenue = batch.tuition_cost
    return total_fixed_cost / (variable_revenue - total_variable_cost)
  end

  def net_income_calc(batch, days)
    quantity = batch.bookings.where(status: "Accepted").count
    total_fixed_cost = total_fixed_cost_calc(batch, days)
    total_variable_cost = batch.costs.where(kind: "Variable").sum(&:amount)
    variable_revenue = batch.tuition_cost
    return (quantity * variable_revenue) - (quantity * total_variable_cost) - total_fixed_cost
  end

  # For graph lines

  def net_income_data(quantity, batch, days)
    arr = []
    count = 0
    quantity.times do
      val = (count * (batch.tuition_cost - batch.costs.where(kind: "Variable").sum(&:amount))) - total_fixed_cost_calc(batch, days).round(2)
      arr << [count, val]
      count += 1
    end
    arr
  end

  def variable_income_data(quantity, batch)
    arr = []
    count = 0
    quantity.times do
      val = count * batch.tuition_cost
      arr << [count, val]
      count += 1
    end
    arr
  end

  def total_cost_data(quantity, batch, days)
    arr = []
    count = 0
    quantity.times do
      val = (count * batch.costs.where(kind: "Variable").sum(&:amount)) + total_fixed_cost_calc(batch, days).round(2)
      arr << [count, val]
      count += 1
    end
    arr
  end

  def variable_cost_data(quantity, batch)
    arr = []
    count = 0
    quantity.times do
      val = count * batch.costs.where(kind: "Variable").sum(&:amount)
      arr << [count, val]
      count += 1
    end
    arr
  end
end

app/views/batches/_add_cost_form.html.erb
<div class="add-modal <%=hidden%>">
  <div class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
      <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

        <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

        <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg">
          <div class="max-w-2xl mx-auto">
            <div class="flex flex-col items-center md:flex-row justify-center">
              <div class="w-full mt-4 md:mt-0 md:w-full">
                <div class="relative z-10 h-auto p-6 overflow-hidden bg-white border-solid border-2 border-gray-100 rounded-lg">
                  <h6 class="mb-6 text-xl font-medium text-center">Add new Cost</h6>
                  <%= simple_form_for [@batch, @cost], class: "" do |f| %>
                  <%= f.input :name,
                              autofocus: true,
                              label: false,
                              placeholder: "Name",
                              input_html: { autocomplete: "off" }, class: "block w-full rounded-lg focus:ring focus:ring-black focus:outline-none" %>

                  <%= f.input :amount,
                              autofocus: true,
                              label: false,
                              placeholder: "Amount",
                              input_html: { autocomplete: "off" }, class: "block w-full rounded-lg focus:ring focus:ring-black focus:outline-none" %>

                  <%= f.input :kind, collection: ["Fixed", "Variable"], prompt: "Type",
                              autofocus: true,
                              label: false,
                              input_html: { autocomplete: "off" }, class: "block w-full rounded-lg focus:ring focus:ring-black focus:outline-none" %>

                  <%= f.input :recurring, collection: ["One Time", "Daily", "Weekly", "Monthly", "Yearly"], selected: 1,
                              autofocus: true,
                              label: false,
                              input_html: { autocomplete: "off" }, class: "block w-full rounded-lg focus:ring focus:ring-black focus:outline-none" %>

                  <%= f.button :submit, "Add", class: "w-full text-sm bg-black cursor-pointer hover:bg-gray-600 text-white mt-0 rounded-lg add-button-form", style: "background-color: #0A2540" %>
                      </div>
                  <% end %>
                  <span class="close-add-modal close-add-modal-x z-10"></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/batches/index.html.erb
<!-- First time access as a student -->

<% if @user.admin == true %>
  <section class="pt-20 pb-0" style="background-color: white">
    <div class="container max-w-6xl mx-auto">
      <h2 class="text-4xl font-medium tracking-normal text-center" style="color: #0A2540">
        Welcome back <%= @user.first_name %>!
      </h2>
      <p class="mt-2 text-lg font-normal text-center" style="color: #0A2540">
        Create and access your cohorts.
      </p>
      <div class="flex justify-center">
        <button class="add_cohort_button my-3 text-white font-normal text-sm py-2 px-4 rounded show-modal">
          Add a new cohort
        </button>
      </div>
      <div class="grid grid-cols-1 gap-4 mt-10 sm:grid-cols-2 lg:grid-cols-2 px-8 w-4/5 mx-auto">
        <% count = 0 %>
        <% @batches.each do |batch| %>
          <%= link_to batch_path(batch) do %>
            <div class="cohort-card relative flex flex-col items-left justify-around col-span-3 px-4 py-4 space-y-2 overflow-hidden sm:rounded-lg bg-white border-2" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 2px;">
              <div class="flex justify-between">
              <div class="h-12 w-12 flex items-center justify-center text-white rounded-full" style="background-color: #0A2540">
                <h4 class="text-bold"><%= batch.name.chars.first %></h4>
              </div>
                <div>
                <h6 class="font-normal text-gray-900 text-right"><span class="font-light" style="color: #0A2540">Start Date:</span><br> <%= batch.start_date %></h6>
                </div>
                </div>
                <h2 class="text-2xl font-medium text-gray-900"><span class="font-light" style="color: #0A2540"></span> <%= batch.name %></h2>
                <div class="flex justify-between items-end">
                <div>
                <h6 class="text-lg font-normal text-gray-900"><span class="font-light" style="color: #0A2540">Tuition Cost:</span><br> €<%= number_with_delimiter(batch.tuition_cost.round, :delimiter => ",") %></h6>
                </div>
                <div>

                <!-- Add if statement for profit and loss -->
                <% if @net_income_arr[count] < 0 %>
                  <span class="font-normal text-red-500">Non Profitable <i class="fas fa-circle animate-pulse"></i> </span>
                <% else %>
                  <span class="font-normal text-green-500">Profitable <i class="fas fa-circle animate-pulse"></i> </span>
                <% end %>
                <!-- Add if statement for profit and loss -->
                </div>
                </div>
              </div>
          <% end %>
          <% count += 1 %>
        <% end %>
      </div>
    </div>
  </section>

  <%= render "form" , hidden:@hidden%>

<!-- First time access as a student -->

<% elsif @user.admin == false && @user.bookings.count == 0 && @user.photo.attached? == false %>
  <section class="pt-40 pb-0 bg-white">
    <div class="container max-w-6xl mx-auto flex flex-col items-center">
      <h2 class="text-4xl font-medium tracking-normal text-center" style="color: #0A2540">
        Welcome <%= @user.first_name %>!
      </h2>
      <p class="mt-2 text-lg text-center" style="color: #0A2540">
        Please upload a profile picture to continue:
      </p>

      <%#-----------image upload --------- %>
      <%= link_to edit_user_registration_path do |f| %>
      <div class="box py-10 px-8 border-2 bg-white border-dashed m-4 opacity-80">
        <button class="w-full text-center add_cohort_button my-2 text-white font-bold text-sm py-2 px-4 rounded show-modal">
        Upload
        </button>
      </div>
      <% end %>

      <% if  @user.photo.key %>
      <div class="box py-10 px-1 border-2 bg-white border-dashed m-4 opacity-80">
        <%= cl_image_tag @user.photo.key, height: 300, width: 400, crop: :fill, style: "margin:auto; width: 50%; border-top-left-radius: 8px; border-top-right-radius: 8px;"%>
      </div>

        <%= simple_form_for ([@booking]), html: { class: 'flex flex-col items-center w-2/5' }  do |f| %>
          <%= f.input :batch_id, label: false, collection: @batches, label_method: lambda{ |batch| "#{batch.name} #{batch.start_date} - #{batch.end_date}" }, :value_method => :id, input_html: { style: 'width:200px;' }, prompt: "Select Cohort"  %>
          <%= f.button :submit, "Apply to cohort", class: "w-4/12 text-center"%>
        <% end %>

      <% end %>
    </div>
  </section>

  <!-- Student has added a photo but it's not in a cohort -->


  <% elsif @user.admin == false && @user.bookings.count == 0 && @user.photo.attached? %>
  <section class="pt-20 pb-0 bg-white">
    <div class="container max-w-6xl mx-auto flex flex-col items-center">
      <h2 class="text-4xl font-medium tracking-normal text-center" style="color: #0A2540">
        Welcome <%= @user.first_name %>!
      </h2>

      <% if  @user.photo.key %>
      <div class="box py-8 px-8 border-2 bg-white border-dashed m-4 opacity-80 w-1/3">
        <%= cl_image_tag @user.photo.key, style: "margin:auto; width: 100%;"%>
      </div>


        <%= simple_form_for ([@booking]), html: { class: 'flex flex-col gap-0 items-center w-2/5' }  do |f| %>
          <%= f.input :batch_id, label: false, collection: @batches, label_method: lambda{ |batch| "#{batch.name} #{batch.start_date} - #{batch.end_date}" }, :value_method => :id, input_html: { style: 'width:200px;' }, prompt: "Select your cohort"  %>
          <%= f.button :submit, "Apply", class: "mt-0 w-4/12 text-center"%>
        <% end %>

      <% end %>
    </div>
  </section>

<!-- Student already in a cohort -->

<% elsif @user.admin == false && @user.bookings.count > 0 %>
  <% if @user.bookings[0].status == "Accepted" %>
    <div id="balloon-container">
  </div>
  <% end %>
  <section class=" pt-40 pb-0 bg-white">
    <div class="container max-w-6xl mx-auto flex flex-col items-center">
      <h2 class="text-4xl font-medium tracking-normal text-center mb-2" style="color: #0A2540">
        Welcome back <%= @user.first_name %>!
      </h2>

      <div class="box rounded-full p-2 border-2 bg-white m-4 w-32" style="margin-bottom: -60px; z-index: 100;">
        <%= cl_image_tag @user.photo.key, class: "rounded-full", style: "margin:auto; width: 100%;"%>
      </div>

    <div class="grid grid-cols-1 gap-4 mt-2 sm:grid-cols-2 lg:grid-cols-2 w-1/3 mx-auto" style="z-index: 10;">
        <% @user.bookings.each do |booking| %>
            <div class="relative flex items-end items-center justify-between col-span-3 px-4 py-4 pt-12 space-y-2 overflow-hidden sm:rounded-xl bg-white border" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 2px;">
            <div class="items-end">
                <h6 class="text-2xl font-normal" style="color: #0A2540"><%= Batch.find(booking.batch_id).name %></h6>
                <h6 class="font-normal" style="color: #0A2540"><%= Batch.find(booking.batch_id).start_date %></h6>
                </div>
                <div class="items-end">

                <% if booking.status == "Pending" %>
                <h6 class="font-normal text-gray-800">Status:
                <h6 class="text-red-400 font-lighter text-right"><%= booking.status %></h6></h6>
                <% else %>
                <h6 class="text-green-400 font-lighter text-right"><p>Congratulations!</p> <p>You have been accepted! 🎉</p></h6></h6>
                <% end %>
                </div>

              </div>
        <% end %>
      </div>
    </div>

  </section>


<% end %>

app/views/batches/show.html.erb
<!-- Header // Do Not Touch -->

<section class="py-10">
  <div class="container max-w-8xl mx-auto">
    <%= link_to batches_path do %>
      <span class="w-20 text-lg bg-transparent font-medium text-start cursor-pointer hover:text-gray-300 rounded-lg" style="color: #0A2540">
        <i class="fas fa-angle-left"></i> Go back
      </span>
    <% end %>
    <h2 class="text-4xl font-medium text-start mt-2" style="color: #0A2540">
      <%= @batch.name %> Dashboard
    </h2>
    <p class="mt-2 text-lg text-start" style="color: #0A2540">
      Review your Students, Costs, and Break Even Point.
    </p>
    <div class="flex gap-2 button-center text-start justify-between">
      <div>
      <%= link_to batch_users_path(@batch) do %>
        <button class="dashboard-main-buttons w-auto text-sm font-normal text-start cursor-pointer py-2 px-4 text-white my-3 rounded-lg mr-2 tracking-wide">
          <%= @batch.name %> Students
        </button>
      <% end %>
      <button
        class="dashboard-main-buttons w-auto text-sm font-normal text-start cursor-pointer py-2 px-4 text-white my-3 rounded-lg mr-2 tracking-wide show-add-modal">
        Add Cost
      </button>
      </div>
      <% if @current_net_income > 0 %>
      <div
        class="w-auto text-sm bg-white font-medium text-start py-2 px-4 text-black my-3 bg-green-100 rounded-full hidden md:block">
        You're passing break even point 👍🏻
      </div>
      <% else %>
        <div
        class="w-auto text-sm bg-white font-medium text-start py-2 px-4 text-black my-3 bg-red-100 rounded-full hidden md:block">
        You're not passing break even point yet
      </div>
      <% end %>
    </div>
  </div>
</section>

<!-- End of Header -->

<div class="thebiggestcontainer">
  <!-- Full Cards Container // Do Not Touch -->
  <div class="container grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 mx-auto gap-8">

    <!-- Numbers Cards Container // Do Not Touch -->
    <section class="grid-cols-1 grid bg-white overflow-hidden rounded-2xl transition duration-500 ease-in-out transform hover:-translate-y-1 border-2" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 2px;">
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">

        <div class="w-full flex flex-col items-start pl-6 pt-4 pb-2 justify-between col-span-4 bg-white overflow-hidden border-b border-gray-100">
          <h6 class="text-xl font-medium text-center" style="color: #0A2540">
            Cohort Data
          </h6>
        </div>


        <div class="w-full flex items-center justify-between px-6 col-span-4 bg-white p-2 overflow-hidden border-b border-gray-200 hover:bg-gray-50">
          <h4 class="text-md font-medium text-left" style="color: #0A2540">
            Amount of students to break even
          </h4>
          <div class="py-1 px-5 text-white bg-yellow-400 rounded-full">
            <h4>
              <%= number_with_delimiter(@break_even, :delimiter=> ",") %>
            </h4>
          </div>
        </div>
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
        <div class="w-full flex items-center justify-between px-6 col-span-4 bg-white p-2 overflow-hidden border-b border-gray-200 hover:bg-gray-50">
          <h4 class="text-md text-left" style="color: #0A2540">
            Net income
          </h4>
          <% if @current_net_income> 0 %>
            <div class="py-1 px-5 text-white bg-green-300 rounded-full">
              <h4>€<%= number_with_delimiter(@current_net_income, :delimiter=> ",") %></h4>
            </div>
          <% elsif @current_net_income < 0 %>
            <div class="py-1 px-5 text-white bg-red-400 rounded-full">
              <h4>€<%= number_with_delimiter(@current_net_income, :delimiter=> ",") %></h4>
            </div>
          <% else %>
            <div class="py-1 px-5 text-gray-700 bg-gray-400 rounded-full">
              <h4>€<%= number_with_delimiter(@current_net_income, :delimiter=> ",") %></h4>
            </div>
          <% end %>
        </div>
      </div>


      <div class="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
        <div
          class="w-full flex items-center justify-between px-6 col-span-4 bg-white p-2 overflow-hidden border-b border-gray-200 hover:bg-gray-50">
          <h4 class="text-md text-left" style="color: #0A2540">
            Number of students in the Cohort
          </h4>
          <div class="py-1 px-5 text-white bg-gray-600 rounded-full">
            <h4>
              <%= number_with_delimiter(@students.count, :delimiter=> ",") %>
            </h4>
          </div>
        </div>
      </div>



        <div class="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
        <div class="w-full flex items-center justify-between px-6 col-span-4 bg-white p-2 overflow-hidden border-b border-gray-200 hover:bg-gray-50">
          <h4 class="text-md text-left" style="color: #0A2540">
            Tutition cost
          </h4>
          <div class="py-1 px-5 text-white bg-gray-600 rounded-full">
            <h4>
              €<%= number_with_delimiter(@batch.tuition_cost, :delimiter=> ",") %>
            </h4>
          </div>
        </div>
      </div>

      <div class="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
        <div
          class="w-full flex items-center justify-between px-6 col-span-4 bg-white p-2 overflow-hidden hover:bg-gray-50">
          <h4 class="text-md text-left" style="color: #0A2540">
            Start date
          </h4>
          <div class="py-1 px-5 text-white bg-gray-600 rounded-full">
            <h4>
              <%= "#{Date.parse(Batch.last.start_date.to_s).day}-#{Date.parse(Batch.last.start_date.to_s).month}-#{Date.parse(Batch.last.start_date.to_s).year}" %>
            </h4>
          </div>
        </div>
      </div>
    </section>
    <!-- End of Numbers Cards Container -->

    <!-- Graph Container // Do Not Touch -->
    <section class="bg-white space-y-1 rounded-xl grid grid-flow-col auto-cols-auto pr-4 py-2 col-span-1 md:col-span-2 transition duration-500 ease-in-out transform hover:-translate-y-1 border-2" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 2px;">
      <div class="self-center euro-sign pl-6">
        <span>€</span>
      </div>
      <div class="self-center cost-graph">
        <% @trial=0 %>
        <%= line_chart ([
          {name: "Net Income" , data: @net_income_data_arr, color: '#10B981' },
          {name: "Variable Cost" , data: @variable_cost_data_arr, color: "#00BFFF" },
          { name: "Revenue (tuition)" , data: @variable_income_data_arr, color: "#FF1493" },
          { name: "Total Cost" , data: @total_cost_data_arr,color: "#FF7F50" }
        ]), points: false, curve: false, xtitle: "Student count" , loading: "Loading...", min: @min_value, max: @max_value
        %>
      </div>
    </section>
    <!-- End of Numbers Cards Container -->

    <div class="container max-w-8xl mx-auto my-0 col-span-1 md:col-span-3 transition duration-500 ease-in-out transform hover:-translate-y-1">
      <div class="rounded-xl bg-white border-2" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 2px;">
        <!-- Costs Table -->
        <section>
          <div>
            <div class="relative flex flex-col bg-white w-full rounded-xl ">
              <div class="">
                <div class="">
                  <div
                    class="rounded-xl w-full flex flex-col items-start pl-6 pt-4 mb-4 justify-between col-span-4 bg-white overflow-hidden">
                    <h3 class="text-xl font-medium text-center" style="color: #0A2540">My Costs</h3>
                  </div>
                </div>
              </div>

              <div class="w-full">
                <table class="bg-transparent w-full table-fixed" >
                  <thead>
                    <tr class="text-sm bg-gray-50" style="color: #0A2540">
                      <th class="align-middle border py-3 uppercase border-l-0 border-r-0 text-left pl-6">
                        Cost name
                      </th>
                      <th class="align-middle border py-3 uppercase border-l-0 border-r-0 text-left">
                        Type
                      </th>
                      <th class="align-middle border py-3 uppercase border-l-0 border-r-0 text-left">
                        Amount
                      </th>
                      <th class="align-middle border py-3 uppercase border-l-0 border-r-0 text-left">
                        Recurring
                      </th>
                      <th class="align-middle border py-3 uppercase border-l-0 border-r-0 text-center">
                        Update
                      </th>
                      <th class="align-middle border py-3 uppercase border-l-0 border-r-0 text-center">
                        Delete
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @costs.each do |cost| %>
                      <tr class="border-b text-left hover:bg-gray-50 h-12" style="color: #0A2540">
                        <th class="border-t-0 align-middle border-l-0 border-r-0 text-left pl-6 font-medium">
                          <%= cost.name %>
                        </th>
                        <td class="border-t-0 align-middle border-l-0 border-r-0 text-left">
                          <%= cost.kind %>
                        </td>
                        <td class="border-t-0 align-center border-l-0 border-r-0 text-left">
                          <%= number_with_delimiter(cost.amount, :delimiter=> ",") %>
                        </td>
                        <td class="border-t-0 align-middle border-l-0 border-r-0 text-left">
                          <%= cost.recurring %>
                        </td>
                        <td class="border-t-0 align-center border-l-0 border-r-0 text-center">
                          <div>
                            <button type="submit"
                              class="text-md px-4 py-1 my-0 bg-transparent cursor-pointer hover:underline rounded-lg show-modal text-center" style="color: #0A2540"
                              data-cost_id="<%=cost.id%>">
                              Update
                            </button>
                          </div>
                        </td>
                        <td class="border-t-0 align-center border-l-0 border-r-0 text-center">
                          <%= simple_form_for [@batch, cost], method: :delete do |f| %>
                            <button type="submit"
                              class="text-md font-medium px-4 py-1 my-0 bg-trasparent cursor-pointer hover:underline text-red-600 rounded-lg text-center"
                              data-cost_id="<%=cost.id%>">
                              Delete
                            </button>
                            <% end %>
                        </td>
                      </tr>
                      <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
    <% @costs.each do |cost| %>
      <%= render "costform" , cost:cost %>
    <% end %>
    <%= render "add_cost_form" , hidden: @hidden_cost %>
  </div>
</div>